# Generated by Django 3.1.2 on 2020-10-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='server',
            fields=[
                ('host', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('port', models.CharField(max_length=6)),
                ('lastCheck', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='container',
            name='userID',
        ),
        migrations.AlterField(
            model_name='container',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
