# Generated by Django 3.1.2 on 2020-10-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0002_auto_20201020_1633'),
    ]

    operations = [
        migrations.DeleteModel(
            name='server',
        ),
        migrations.AddField(
            model_name='container',
            name='image',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='container',
            name='names',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='container',
            name='os',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='container',
            name='server',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
