# Generated by Django 3.1.2 on 2020-10-24 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_auto_20201021_1205'),
        ('containers', '0003_auto_20201024_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='id',
            field=models.CharField(max_length=250, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='names',
            field=models.CharField(default=None, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.server'),
        ),
    ]
