# Generated by Django 3.1.2 on 2020-10-24 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0004_auto_20201025_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='lastCheck',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
