# Generated by Django 3.1.2 on 2020-10-24 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0005_container_lastcheck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='server',
            new_name='container_server',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='names',
            new_name='name',
        ),
    ]
