# Generated by Django 3.1.2 on 2020-10-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='dataAdded',
            new_name='dateCreated',
        ),
        migrations.AlterField(
            model_name='server',
            name='host',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='port',
            field=models.PositiveIntegerField(),
        ),
    ]
